create mvp desktop
Poldyaich97/admtalk pull request #1
Opened 2023-02-11 11:08 UTC by Poldyaich97

2023-02-13 22:01 UTC, chervyakovru requested changes

2023-02-13 22:01 UTC, chervyakovru commented on package.json
>      "@types/react-dom": "^18.0.0",
пакеты @types нужны только для разработки. Лучше унести их в devDependencies

2023-02-13 22:01 UTC, chervyakovru commented on src/Container/Container.module.css
> +.container {
Лишний файл?

2023-02-13 22:01 UTC, chervyakovru commented on src/Header/Header.tsx
> +/* eslint-disable react/no-unknown-property */
Нет нужды отключать eslint тут

2023-02-13 22:01 UTC, chervyakovru commented on src/Container/Container.module.css
> +.container {
Можно сделать из этого компонент (просто div с классом) и добавалять его туда где нужен контейнер

2023-02-13 22:01 UTC, chervyakovru commented on src/Header/Header.module.css
> +  padding: 0px 16px;
> Можно сделать из этого компонент (просто div с классом) и добавалять его туда где нужен контейнер

Чтобы вот такие стили не дублировать

2023-02-13 22:01 UTC, chervyakovru commented on src/Header/Header.tsx
> +            <a href='/kiosks'>
Лучше изменить на <Link />

2023-02-13 22:01 UTC, chervyakovru commented on src/Main/Card/Card.tsx
> +            <p className={stylesCard.description}>{props.description || ''}</p>
в выражении `|| ''` нет нужды. Без этого будет тоже самое

2023-02-13 22:01 UTC, chervyakovru commented on src/Main/Kiosk/Common/Common.tsx
> +  console.log(props)
console.log

2023-02-13 22:01 UTC, chervyakovru commented on src/Main/Kiosk/Common/Common.tsx
> +const linkStyle = {
не используется?

2023-02-13 22:01 UTC, chervyakovru commented on src/Main/Kiosk/Kiosk.tsx
> +  const array = location.pathname.split('/')
не удачное название переменной. назови более специфично

2023-02-13 22:01 UTC, chervyakovru commented on src/Main/Kiosk/Kiosk.tsx
> +              <div className={styles.left_btn}>
```
<div className={styles.left_btn}>
  <Link className={commonIsActive ? styles.btn_active : ''} to={`${url}/common`}>
    Общие
  </Link>
</div>
```

Выглядит как компонент у которого меняются только to и text. Давай вынесем

2023-02-13 22:01 UTC, chervyakovru commented on src/Main/Kiosk/Kiosk.tsx
> +}
Весь код работы с сетью стоит унести в отдельный файл. Например `api.ts` в корне `src`

2023-02-13 22:01 UTC, chervyakovru commented on src/Main/Main.tsx
> +export default function Header() {
Наверное это не Header?

2023-02-13 22:01 UTC, chervyakovru commented on src/Main/Main.tsx
> +function Kiosks() {
Лучше вынести в отдельный файл

2023-02-13 22:01 UTC, chervyakovru commented on src/Main/Main.tsx
> +        <ThemeContext.Provider value={DARK_THEME}>
Думаю стоит `ThemeContext.Provider` вынести поближе к корню приложения

2023-02-13 22:01 UTC, chervyakovru commented on src/Main/Main.tsx
> +              return e.description.indexOf(filter) != -1
проще заиспользовать `.includes`

2023-02-13 22:01 UTC, chervyakovru commented on src/Main/Main.tsx
> +              return e.description.indexOf(filter) != -1
у тебя одна и та же строчка 2 раза повторяется. Давай подумаем как упростить

2023-02-13 22:01 UTC, chervyakovru commented on src/Main/Main.tsx
> +                name={element.title || element.machineName}
Возможно стоит в карточку отправлять весь element, а не все поля по отдельности

2023-02-13 22:01 UTC, chervyakovru commented on src/Main/Main.tsx
> +}
вынести в файл `api.js`

2023-02-13 22:01 UTC, chervyakovru commented on src/Main/Navigation/Navigation.module.css
> +ul {
css modules предполагают что все селекты будут состоять из классов. Сейчас же эти стили пролезли наружу и заафектили все приложение. Не надо так

2023-02-15 08:44 UTC, Poldyaich97 commented on package.json
>      "@types/react-dom": "^18.0.0",
Done

2023-02-16 11:59 UTC, chervyakovru commented on src/App.tsx
> +  FLAT_THEME_8PX_OLD,
/wtd remove this imports

2023-02-16 12:01 UTC, chervyakovru commented on src/App.tsx
> -export default App;
/wtd replace function with const

2023-03-05 06:46 UTC, Poldyaich97 commented on src/Header/Header.tsx
> +            <a href='/kiosks'>
done

2023-03-05 06:47 UTC, Poldyaich97 commented on src/Main/Card/Card.tsx
> +            <p className={stylesCard.description}>{props.description || ''}</p>
Там была незаконченная идея.  
Переделал.

2023-03-05 06:52 UTC, Poldyaich97 commented on src/Main/Kiosk/Common/Common.tsx
> +const linkStyle = {
done

2023-03-05 06:52 UTC, Poldyaich97 commented on src/Main/Kiosk/Kiosk.tsx
> +  const array = location.pathname.split('/')
done

2023-03-11 10:49 UTC, Poldyaich97 commented on src/Main/Main.tsx
> +}
done

2023-03-11 10:55 UTC, Poldyaich97 commented on src/Container/Container.module.css
> +.container {
done

2023-03-14 08:21 UTC, Poldyaich97 commented on src/Header/Header.module.css
> +  padding: 0px 16px;
Done

2023-03-14 08:22 UTC, Poldyaich97 commented on src/Main/Kiosk/Kiosk.tsx
> +}
Done

2023-03-14 08:45 UTC, Poldyaich97 commented on src/Main/Main.tsx
> +              return e.description.indexOf(filter) != -1
done

2023-03-14 08:56 UTC, Poldyaich97 commented on src/Main/Navigation/Navigation.module.css
> +ul {
done

2023-03-14 08:57 UTC, Poldyaich97 commented on src/Main/Main.tsx
> +              return e.description.indexOf(filter) != -1
done

2023-03-14 09:24 UTC, Poldyaich97 commented on src/Main/Main.tsx
> +export default function Header() {
done

2023-03-14 09:29 UTC, Poldyaich97 commented on src/Main/Kiosk/Common/Common.tsx
> +  console.log(props)
done

2023-03-14 19:58 UTC, Poldyaich97 commented on src/Main/Main.tsx
> +                name={element.title || element.machineName}
done

2023-03-16 12:52 UTC, Poldyaich97 commented on src/Main/Kiosk/Kiosk.tsx
> +              <div className={styles.left_btn}>
done

2023-03-16 18:14 UTC, Poldyaich97 commented on src/Main/Main.tsx
> +function Kiosks() {
done

2023-03-16 18:14 UTC, Poldyaich97 commented
Done

2023-03-16 18:15 UTC, merged