Feat/mobile
Poldyaich97/admtalk pull request #2
Opened 2023-03-18 16:02 UTC by Poldyaich97

creating a mobile version

2023-03-20 18:38 UTC, chervyakovru commented on src/Main/Card/Card.module.css
> +  .namePC {
/wtd remove selector

2023-03-20 18:39 UTC, chervyakovru commented on src/Main/Card/Card.module.css
> +   }
/wtd remove this

2023-03-20 19:00 UTC, chervyakovru requested changes

2023-03-20 19:00 UTC, chervyakovru commented on src/Main/Card/Card.tsx
>  const Card: React.FC<any> = (props) => {
Нужно any заменить на интерфейс props

2023-03-20 19:00 UTC, chervyakovru commented on src/Main/Card/Card.module.css
>    font-size: 18px;
Давай переиспользуемые числа вынесем в переменные https://developer.mozilla.org/ru/docs/Web/CSS/Using_CSS_custom_properties

Особенно те, что касаются media выражений, размеров шрифтов, цвета

2023-03-20 19:00 UTC, chervyakovru commented on src/Main/Kiosk/Kiosk.tsx
>  const Kiosk: React.FC<any> = () => {
any нужно убрать

2023-03-20 19:00 UTC, chervyakovru commented on src/Main/Kiosk/Kiosk.tsx
>                  <Route path={`${path}/other`}>
Что будет по этому url?

2023-03-20 19:00 UTC, chervyakovru commented on src/Main/Kiosk/LeftBtn/LeftBtn.tsx
> +const LeftBtn: React.FC<any> = (props) => {
нужно заменить any интерфейсом пропсов

2023-03-20 19:00 UTC, chervyakovru commented on src/Main/Kiosk/LeftBtn/LeftBtn.tsx
название Left, Top, Up, etc плохо. Что если в мобильной версии кнопка будет уезжать вниз и в середину? Что если захочешь переиспользовать этот компонент? Что если слева нужно будет добавить вторую кнопку?
Назови более семантично

2023-03-20 19:00 UTC, chervyakovru commented on src/Main/Kiosk/NavigationKiosk/NavigationKiosk.module.css
> +    } */
/wtd remove this

2023-03-20 19:00 UTC, chervyakovru commented on src/Main/Kiosk/NavigationKiosk/NavigationKiosk.tsx
> +const NavigationKiosk: React.FC<any> = (props) => {
any

2023-03-20 19:00 UTC, chervyakovru commented on src/Main/Kiosks/Kiosks.tsx
> +    {
Можно вынести в интерфейс Kiosk и переиспользовать в других компонентах

2023-03-20 19:00 UTC, chervyakovru commented on src/Main/Kiosks/Kiosks.tsx
> +      const kiosk = await getData(`?pageSize=1000`)
стоит обработать случай возникновения ошибки

2023-03-20 19:00 UTC, chervyakovru commented on src/Main/Kiosks/Kiosks.tsx
> +          .filter((e) => (e.description ?? '').indexOf(filter) !== -1)
чуть семантичнее использовать тут includes вместо indexOf

2023-03-20 19:00 UTC, chervyakovru commented on src/Main/Kiosks/Kiosks.tsx
> +            <div key={pos}>
Использовать индексов для key неправильно. Почему и что использовать вместо можно прочитать тут https://ru.reactjs.org/docs/lists-and-keys.html#keys

2023-03-20 19:00 UTC, chervyakovru commented on src/Main/Main.tsx
> +/* eslint-disable @typescript-eslint/no-unused-vars */
😑

2023-03-20 19:00 UTC, chervyakovru commented on src/Main/Main.tsx
> +      <div className={`${containerStyle.container} + ${styles.containerWidth}`}>
тут не нужны ни >> ни +. Это шаблонная строка https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Template_literals

2023-03-20 19:01 UTC, chervyakovru commented on src/Main/Kiosk/NavigationKiosk/NavigationKiosk.module.css
> +    } */
Можешь тут просто кнопку commit нажать и он уберет этот коммент за тебя

2023-03-22 15:52 UTC, Poldyaich97 commented on src/Main/Kiosks/Kiosks.tsx
> +            <div key={pos}>
/wtf replace key with element id

2023-03-22 15:54 UTC, Poldyaich97 commented on src/Main/Kiosks/Kiosks.tsx
> +            <div key={pos}>
/wtd replace key with element id

2023-03-22 15:54 UTC, Poldyaich97 commented on src/Main/Main.tsx
> +      <div className={`${containerStyle.container} + ${styles.containerWidth}`}>
/wtd remove + from className

2023-03-22 15:56 UTC, Poldyaich97 commented on src/Main/Kiosks/Kiosks.tsx
> +            <div key={pos}>
/wtd replace value of "key" attribute with element.id

2023-06-19 16:15 UTC, merged